version: '3'

services:
  backend.org1:
    container_name: backend.org1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ORG=org1
    network_mode: host
    environment:
      - PORT=8001
      - JWT_SECRET=Yd/njsslMl?iw:m;17H#%Ce:nMPxDn^WP&BGCo38hfnCvp":##.:r}ap+!H23>;
      - ORG_MSP=Org1MSP
      - ORG_DOMAIN=org1.example.com
      - ORG_ADMIN=admin-org1
      - ORG_PASSWORD=PASSWORD1
      - APP_ADMIN=org1
      - ORG_NAME=Pelabuhan
    command: sh -c "rm -rf node_modules && yarn install && yarn enroll-admin && yarn start"
  backend.org2:
    container_name: backend.org2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ORG=org2
    network_mode: host
    environment:
      - PORT=8002
      - JWT_SECRET=Yd/njsslMl?iw:m;17H#%Ce:nMPxDn^WP&BGCo38hfnCvp":##.:r}ap+!H23>;
      - ORG_MSP=Org2MSP
      - ORG_DOMAIN=org2.example.com
      - ORG_ADMIN=admin-org2
      - ORG_PASSWORD=PASSWORD2
      - APP_ADMIN=org2
      - ORG_NAME=Unit Pengolahan Ikan (UPI)
    command: sh -c "rm -rf node_modules && yarn install && yarn enroll-admin && yarn start"


